### ISSUE TITLE
config_datasets.json is not created

### ISSUE THREAD

**Issue by brekelbende** [adswerve/google_analytics_flattener_ga4#18] opened 2023-01-26 18:32 UTC
Deployment says ok, no errors. all completed but no config is created in the bucket. 
Manually adding one and backfilling worked after adding some python modules. But i'm worried that pub/sub won't work
BQ rights seem to be ok. Any clue?

**Comment by iamnutzy1975** [comment] 2023-01-26 18:41
Could be a permission issue that needs to be resolved.  What user and
predefined roles were used?

**Comment by RuslanBergenov** [comment] 2023-01-26 20:56
@brekelbende , can you check the logs to see if there was any errors?

**Comment by brekelbende** [comment] 2023-01-27 11:15
This should be ok, i guess
[image: image.png]

**Comment by brekelbende** [comment] 2023-01-27 11:19
I have this error in the Cloud function log

  File
"/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/_http.py",
line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET
https://bigquery.googleapis.com/bigquery/v2/projects/********/queries/b42d992b-0a7e-431e-b65c-fce80a327276?maxResults=0&location=US&prettyPrint=false:
EXECUTE IMMEDIATE sql string cannot be NULL at [2:27]

(job ID: b42d992b-0a7e-431e-b65c-fce80a327276)


     -----Query Job SQL Follows-----


    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   .    |    .    |    .    |    .    |    .    |    .    |    .    |    .
   |    .    |    .    |    .    |
   1:
   2:        EXECUTE IMMEDIATE (
   3: WITH schemas AS (
   4:  SELECT
   5:    schema_name,
   6:    LAST_VALUE(schema_name) OVER (PARTITION BY catalog_name ORDER BY
schema_name ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
AS last_schema
   7:  FROM
   8:    INFORMATION_SCHEMA.SCHEMATA
   9:  where regexp_contains(schema_name,r'^analytics\_\d+$')
  10:), static AS (
  11:  SELECT
  12:    "SELECT dataset_id FROM `%s.__TABLES__` where
regexp_contains(table_id,r'^events.*\\d{8}$') and
((UNIX_MILLIS(current_timestamp()) - creation_time)/1000)/86400 < 30 group
by 1" AS sql,
  13:    " union all " AS cmd_u,
  14:    " order by 1 " AS cmd_f
  15:)
  16:SELECT
  17:  ARRAY_TO_STRING(ARRAY_AGG(sql_command_rows),"") AS
generated_sql_statement
  18:FROM (
  19:  SELECT
  20:    CASE WHEN schemas.schema_name != schemas.last_schema THEN
CONCAT(FORMAT(static.sql,schema_name),static.cmd_u)
  21:         ELSE CONCAT(FORMAT(static.sql,schema_name),static.cmd_f)
  22:     END AS sql_command_rows
  23:  FROM
  24:    static
  25:  CROSS JOIN
  26:    schemas
  27:  ORDER BY
  28:    schema_name ASC
  29:      ) -- end of sub select
  30:);  --end of dynamic SQL statement
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   .    |    .    |    .    |    .    |    .    |    .    |    .    |    .
   |    .    |    .    |    .    |


Met vriendelijke groet,

Paul Brekelmans
Senior Online Marketeer | Kaliber | +316 270 77 520

**Comment by RuslanBergenov** [comment] 2023-02-01 20:33
@brekelbende, I have seen that error before, it happens when there's no recent (within the last 30 days) GA4 data in BigQuery. 

Are you exporting any GA4 properties into your GCP project's BigQuery?

In your BigQuery, do you have any datasets called `analytics_{ga4_property_id}` with tables called `events_{date}`, where table date is within the last 30 days?

If the answer is no, then the following query will fail and therefore no flattener config file will be created.


```
        EXECUTE IMMEDIATE (
 WITH schemas AS (
  SELECT
    schema_name,
    LAST_VALUE(schema_name) OVER (PARTITION BY catalog_name ORDER BY schema_name ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_schema
  FROM
    INFORMATION_SCHEMA.SCHEMATA 
  where regexp_contains(schema_name,r'^analytics\_\d+$')
), static AS (
  SELECT
    "SELECT dataset_id FROM `%s.__TABLES__` where regexp_contains(table_id,r'^events.*\\d{8}$') and ((UNIX_MILLIS(current_timestamp()) - creation_time)/1000)/86400 < 30 group by 1" AS sql,
    " union all " AS cmd_u,
    " order by 1 " AS cmd_f 
)
SELECT
  ARRAY_TO_STRING(ARRAY_AGG(sql_command_rows),"") AS generated_sql_statement
FROM (
  SELECT
    CASE WHEN schemas.schema_name != schemas.last_schema THEN CONCAT(FORMAT(static.sql,schema_name),static.cmd_u)
         ELSE CONCAT(FORMAT(static.sql,schema_name),static.cmd_f)
     END AS sql_command_rows
  FROM
    static
  CROSS JOIN
    schemas
  ORDER BY
    schema_name ASC
      ) -- end of sub select
);  --end of dynamic SQL statement

```

**Comment by brekelbende** [comment] 2023-02-03 13:45
@RuslanBergenov yes, i have those datasets and events and intraday tables populated with recent data. Could gcloud locations be a thing? I build my buckets in europe-west4. My dataset is also in europe-west4.

**Comment by RuslanBergenov** [comment] 2023-02-03 16:49
@brekelbende, not sure if location causes it, but can't rule it out either.

Can you try the following investigation steps?

1) Run the above SQL query in BigQuery, in the GCP project you installed the flattener to. Does it give you the same error? 

2) Trigger the `cfconfigbuilder` Cloud Function manually. Go to 
- Cloud Functions
- Click on` {deployment-name}-cfconfigbuilder` Cloud Function
- Go to `TESTING`
- Click `TEST THE FUNCTION`
- Check Cloud Logging. Search for logs containing the Cloud Function name `{deployment-name}-cfconfigbuilder `
- Did the same error happen?
- Was the config file built?

**Comment by RuslanBergenov** [comment] 2023-02-03 16:51
Can you verify that the following steps were completed before the installation?

As the installing user for [PROJECT_ID], enable the following APIs

- Cloud Build API
- Cloud Deployment Manager V2 API
- Cloud Functions API
- Identity and Access Management (IAM) API
- Cloud Scheduler API (if you need to flatten intraday tables)


As the installing user for [PROJECT_ID], grant the following pre-defined IAM roles to [PROJECT_NUMBER]@cloudservices.gserviceaccount.com (built in service account) otherwise deployment will fail with permission errors. See https://cloud.google.com/deployment-manager/docs/access-control for detailed explanation.

- Logs Configuration Writer
- Cloud Functions Developer
- Pub/Sub Admin

**Comment by brekelbende** [comment] 2023-02-03 19:11
>
>
>    1.
>
>    Run the above SQL query in BigQuery, in the GCP project you installed
>    the flattener to. Does it give you the same error?
>    2.
>
>    Trigger the cfconfigbuilder Cloud Function manually. Go to
>
>
>    - Cloud Functions
>    - Click on {deployment-name}-cfconfigbuilder Cloud Function
>    - Go to TESTING
>    - Click TEST THE FUNCTION
>    - Check Cloud Logging. Search for logs containing the Cloud Function
>    name {deployment-name}-cfconfigbuilder
>    - Did the same error happen?
>    - Was the config file built?
>
>
Same error, no config was built.


>    - Cloud Build API
>    - Cloud Deployment Manager V2 API
>    - Cloud Functions API
>    - Identity and Access Management (IAM) API
>    - Cloud Scheduler API (if you need to flatten intraday tables)
>
> As the installing user for [PROJECT_ID], grant the following pre-defined
> IAM roles to ***@***.*** (built in
> service account) otherwise deployment will fail with permission errors. See
> https://cloud.google.com/deployment-manager/docs/access-control for
> detailed explanation.
>
>    - Logs Configuration Writer
>    - Cloud Functions Developer
>    - Pub/Sub Admin
>
>
Yeah, I did all that. This query is indeed the problem. I'm trying to debug
it.

>
> EXECUTE IMMEDIATE (
> WITH schemas AS (
> SELECT
> schema_name,
> LAST_VALUE(schema_name) OVER (PARTITION BY catalog_name ORDER BY
> schema_name ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
> AS last_schema
> FROM
> INFORMATION_SCHEMA.SCHEMATA
> where regexp_contains(schema_name,r'^analytics\_\d+$')
> ), static AS (
> SELECT
> "SELECT dataset_id FROM `%s.__TABLES__` where
> regexp_contains(table_id,r'^events.*\\d{8}$') and
> ((UNIX_MILLIS(current_timestamp()) - creation_time)/1000)/86400 < 30 group
> by 1" AS sql,
> " union all " AS cmd_u,
> " order by 1 " AS cmd_f
> )
> SELECT
> ARRAY_TO_STRING(ARRAY_AGG(sql_command_rows),"") AS generated_sql_statement
> FROM (
> SELECT
> CASE WHEN schemas.schema_name != schemas.last_schema THEN
> CONCAT(FORMAT(static.sql,schema_name),static.cmd_u)
> ELSE CONCAT(FORMAT(static.sql,schema_name),static.cmd_f)
> END AS sql_command_rows
> FROM
> static
> CROSS JOIN
> schemas
> ORDER BY
> schema_name ASC
> ) -- end of sub select
> ); --end of dynamic SQL statement


I can run other queries on the dataset and tables. So it's weird. Must be
something small. Will try the exact table names instead of regex's.
Tommorrow.

Thanks for thinking along so far :-)

**Comment by RuslanBergenov** [comment] 2023-02-06 23:54
@brekelbende, what happens when you run the very first part of the query?

```
  SELECT
    schema_name,
    LAST_VALUE(schema_name) OVER (PARTITION BY catalog_name ORDER BY schema_name ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_schema
  FROM
    INFORMATION_SCHEMA.SCHEMATA 
  where regexp_contains(schema_name,r'^analytics\_\d+$')
```

**Comment by brekelbende** [comment] 2023-02-07 07:46
@RuslanBergenov found it! It's the processing location of the query.  Under Query Settings > Advanced Settings > Automatic location selection was "checked". My dataset is in europe-west4 but automatic choose US. So it couldn't find the dataset. Is that something i can force within the code?

**Comment by RuslanBergenov** [comment] 2023-02-08 00:46
@brekelbende, you were correct a couple of days ago - the root cause of the issue does appear to be location. 

Can you try deploying the Cloud Functions to europe-west4? 

Uninstall the flattener: 
gcloud deployment-manager deployments delete ga-flattener-deployment  -q

In ga_flattener.yaml, replace us-east1 location with europe-west4

Deploy the flattener again:gcloud deployment-manager deployments create ga-flattener-deployment --config ga_flattener.yaml

Does that work for you?

**Comment by RuslanBergenov** [comment] 2023-02-08 00:56
@brekelbende, based on this documentation, looks like you wouldn't be able to deploy to europe-west4, because it's only for Generation 2 Cloud Functions. 

https://cloud.google.com/functions/docs/locations

Try deploying the Cloud Functions to to europe-west2. I'm curious about 3 things:
- Does the flattener get installed?
- Does the config file gets build? 
- Would the flattening queries run successfully?

**Comment by brekelbende** [comment] 2023-02-09 10:20
@RuslanBergenov unfortunately, it doesn't work. It's get installed. Won't built the config.json file in the adswerve bucket. I've also set everything in the code to europe-west2 or EU regions. Still fails to execute the query from INFORMATION_SCHEMA.SCHEMATA. It only works when BQ dataset is in europe-west-2 I guess. Current client cannot host outside NL(=europe-west4) . Manually adding the config_dataset.json works fine btw.

**Comment by RuslanBergenov** [comment] 2023-02-09 19:34
@brekelbende, sorry to hear about the challenges you've been experiencing. Good idea to just add the config file manually. Follow the examples in the repo and README and add your actual GA4 property id in it.  

Check tomorrow to see if the daily flattening job ran. You can also try running a backfill job (see README) for instructions. 

Look for flat tables in BigQuery and also check cloud functions logs for any errors. 

Let me know how it goes.

**Comment by RuslanBergenov** [comment] 2023-03-21 20:52
@brekelbende, were you able to figure out the issues you were having? Do you have any other questions?

**Comment by brekelbende** [comment] 2023-03-22 07:27
@RuslanBergenov unfortunately no, i'm a bit tangled into GCP locations en cloud function versions. But it's only the deployment. Manually altering the config.json works fine though and the process keeps running.

**Comment by RuslanBergenov** [comment] 2023-07-19 19:15
@brekelbende, I will close this issue for now, but we can reopen it if you need any help on this issue.

**Closed by RuslanBergenov** 2023-07-19 19:15 UTC
